// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nvd_231230727_de02.Data;

#nullable disable

namespace nvd_231230727_de02.Migrations
{
    [DbContext(typeof(Ngovandung231230727De02Context))]
    [Migration("20251024141612_Fix_NvdId_Identity")]
    partial class Fix_NvdId_Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nvd_231230727_de02.Models.NvdCatalog", b =>
                {
                    b.Property<int>("NvdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nvdId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NvdId"));

                    b.Property<bool?>("NvdCateActive")
                        .HasColumnType("bit")
                        .HasColumnName("nvdCateActive");

                    b.Property<string>("NvdCateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nvdCateName");

                    b.Property<decimal>("NvdCatePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nvdCatePrice");

                    b.Property<int>("NvdCateQty")
                        .HasColumnType("int")
                        .HasColumnName("nvdCateQty");

                    b.Property<string>("NvdPicture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nvdPicture");

                    b.HasKey("NvdId")
                        .HasName("PK__NvdCatal__CA45E3779A41E60A");

                    b.ToTable("NvdCatalog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
